version: "3.8"

services:
    db:
        image: postgres:16
        container_name: trabalhofinaldb
        ports:
            - "5435:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: trabalhofinaldb
        volumes:
            - trabalhofinaldb_data:/var/lib/postgresql/data
        networks:
            - trabalhofinal-network

volumes:
    trabalhofinaldb_data:

networks:
    trabalhofinal-network:
